version: "3"

services:
  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    entrypoint: php
    user: php
    tty: true
    stdin_open: true
    working_dir: /home/php
    volumes:
      - .:/home/php

  composer:
    extends: php
    entrypoint: composer
